apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-cart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" #this controls deployment order if db is 0, backend is 1 and frontend is 2 then 
spec:
  project: retail-store
  source:
    repoURL: https://github.com/LondheShubham153/retail-store-sample-app
    targetRevision: gitops
    path: src/cart/chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
